### PR TITLE
fix: pnpm-lock

### PR DESCRIPTION
**Pull request by auer-martin**
The ci fails currently when publishing the packages.

```
lerna ERR! EUNCOMMIT Working tree has uncommitted changes, please commit or remove the following changes before continuing:
lerna ERR! EUNCOMMIT  M pnpm-lock.yaml
lerna ERR! EUNCOMMIT ?? .npmrc
```

I am unsure, but I think this may have been caused by a different PNPM version I used.

### CODE REVIEW

**Review by TimoGlastra — APPROVED** [review]
Yeah the pnpm lock version is still on v6, which is quite old. Would be good to upgrade to a newer version

**Comment by TimoGlastra** [comment]
@nklomp bump on this one

**Comment by nklomp** [comment]
We are using pnpm 8 internally, because 9 was not stable at that point. Given the impact on the other repo's and CI/CD this needs to be concerted. So unlikely we will be able to do that today

**Comment by TimoGlastra** [comment]
@auer-martin can you update this to pnpm 8? Or at least the same version as the ci, then it shouldn't cause issues

**Comment by auer-martin** [comment]
I did update to version 8 for compatibility, right? So this should work?

**Comment by TimoGlastra** [comment]
Ah wait, okay this reverts the 9.0 lockfile back to 8. Okay then we should merge this yes.

**Pull request merged**
