### PR TITLE
feat: add support for verifying multi-vp presentations

### PR DESCRIPTION
**Pull request by TimoGlastra**
Adds support for verifying multi-vp presentations based on the recent addition to PEX. it does not add methods yet to create responses including multiple VPs, as this would require more changes to PEX as well. Currently how we do it in Credo is we determine the presentations we need to create based on the credentials (each sd-jwt one, each credentialSubject.id in jwt-vp one, etc..). And then we can call the evaluatePresentations to generate the submission. We should probably contribute that to PEX?

But this PR at least allows the verifying and handling of multi-vp responses. Currently based on unstable version of PEX, need a new release as well.

### CODE REVIEW

**Comment by TimoGlastra** [comment]
@sksadjad / @sanderPostma if you also have time to look at this one, that'll be helpful. It will unblock quite a few things for us :)

**Comment by sanderPostma** [comment]
No comments on the code itself, but going to build & release a new pex library first on which this branch depends on.
Also the tests are failing, please see if this is related to your changes, otherwise I will also create a branch feat/multi-presentation in our repo it base the PR against.

**Comment by TimoGlastra** [comment]
> Also the tests are failing, please see if this is related to your changes

Yes I coded this in the plane and some tests were failing due to missing internet, but I see now that there's some issues in those tests still. I will fix them!

**Comment by TimoGlastra** [comment]
Fixed the test @sanderPostma, passes locally now

**Comment by TimoGlastra** [comment]
Ah and also in the CI now 🎉

**Comment by TimoGlastra** [comment]
Updated with latest version of PEX. It now needs https://github.com/Sphereon-Opensource/PEX/pull/169 and https://github.com/Sphereon-Opensource/PEX/pull/168 to be merged/release first

**Comment by sanderPostma** [comment]
@TimoGlastra 
I merged it, but apparently we had an increase in test coverage because tsc is now complaining about a lot of things when compiling from AuthenticationResponse.response.spec.ts
(working on it in https://github.com/Sphereon-Opensource/OID4VC/compare/develop...fix/post-merge )

**Pull request merged**
